dist: trusty
sudo: true
language: generic

install:
- sudo add-apt-repository --yes ppa:openscad/releases
- sudo apt-get update -qq
- sudo DEBIAN_FRONTEND=noninteractive apt-get install -y openscad inkscape imagemagick xvfb
- sudo apt-get purge -y fglrx
- sudo pip install svg.path==2.2

script:
- xvfb-run --auto-servernum --server-args "-screen 0 1024x768x24" python -u ./scripts/generate_gif.py assembly.scad assembly.gif 350
- mv build/animation/assembly.gif build/
- xvfb-run --auto-servernum --server-args "-screen 0 1024x768x24" python -u ./scripts/generate_gif.py base.scad base.gif 200
- mv build/animation/base.gif build/
- xvfb-run --auto-servernum --server-args "-screen 0 1024x768x24" python -u ./scripts/generate_gif.py module_empty.scad module_empty.gif 200
- mv build/animation/module_empty.gif build/
- python -u ./scripts/generate_stl.py
- find build

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
    cd build
    git init
    git checkout -b gh-pages
    git add assembly.gif
    git add base.gif
    git add module_empty.gif
    git -c user.name='Build Bot' -c user.email='travis' commit -m 'Updated animations'
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    git push -f -q https://muesli:$GITHUB_API_KEY@github.com/muesli/modular-case.git gh-pages &>/dev/null
    cd "$TRAVIS_BUILD_DIR"
  fi
